// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSlXt1THqQuxiPwOOjRm0eacHyAKOa330',
    appId: '1:586054177248:web:46564db751e5f1f82d5b85',
    messagingSenderId: '586054177248',
    projectId: 'surakshith-5a9e1',
    authDomain: 'surakshith-5a9e1.firebaseapp.com',
    storageBucket: 'surakshith-5a9e1.firebasestorage.app',
    measurementId: 'G-0NRKXRVM62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAKz2Lgxhu3nZigekDwUpkNr2lKg_YL_Y',
    appId: '1:586054177248:android:ddf70065f89e78272d5b85',
    messagingSenderId: '586054177248',
    projectId: 'surakshith-5a9e1',
    storageBucket: 'surakshith-5a9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-w5dWWjmGoHlSt_FAxr4lOjD4NHe3FA',
    appId: '1:586054177248:ios:6dd2dcd0d185862c2d5b85',
    messagingSenderId: '586054177248',
    projectId: 'surakshith-5a9e1',
    storageBucket: 'surakshith-5a9e1.firebasestorage.app',
    iosBundleId: 'com.example.surakshith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-w5dWWjmGoHlSt_FAxr4lOjD4NHe3FA',
    appId: '1:586054177248:ios:6dd2dcd0d185862c2d5b85',
    messagingSenderId: '586054177248',
    projectId: 'surakshith-5a9e1',
    storageBucket: 'surakshith-5a9e1.firebasestorage.app',
    iosBundleId: 'com.example.surakshith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSlXt1THqQuxiPwOOjRm0eacHyAKOa330',
    appId: '1:586054177248:web:c9510b054d58c5002d5b85',
    messagingSenderId: '586054177248',
    projectId: 'surakshith-5a9e1',
    authDomain: 'surakshith-5a9e1.firebaseapp.com',
    storageBucket: 'surakshith-5a9e1.firebasestorage.app',
    measurementId: 'G-BZC355514Z',
  );
}
